### PR TITLE
Add netcoreapp target

### PR DESCRIPTION
**Pull request by Liklainy**
* Changed to sdk style
* Added netcoreapp targets
* Merged nuspec props to csproj
* Changed tasks.py to update version in csproj
* Changed to dotnet build and pack in azure-pipelines

### CODE REVIEW

**Comment by kenjiuno** [comment]
Thanks i'll test this

**Comment by Liklainy** [comment]
Sorry, It seems I have broken your pipeline 😔
Do I need to update tests too?

**Comment by kenjiuno** [comment]
@Liklainy 
Thanks for looking at this.
I have some ideas and I'll test it first.
I'll let you know if I need helps about .NET Core part!

**Comment by kenjiuno** [comment]
Thanks, I have merged your changes with fixing tests. Now published at nuget:

```txt
kenjiuno.PdfSharp-WPF 1.31.5584
kenjiuno.PdfSharp.Xps 1.1.6
```

**Comment by Liklainy** [comment]
👍 Great! 😄
Thank you, you’re amazing!

**Pull request merged**
